# Generated by Django 5.0.3 on 2024-07-10 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='ExpenseCategory',
        ),
    ]
