# Generated by Django 5.1 on 2024-08-21 09:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_expensecategory_alter_expense_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='expensecategory',
            name='name',
            field=models.CharField(choices=[('Food', 'Food'), ('Transportation', 'Transportation'), ('Utilities', 'Utilities'), ('Entertainment', 'Entertainment'), ('Healthcare', 'Healthcare'), ('Education', 'Education'), ('Other', 'Other')], max_length=100),
        ),
        migrations.AlterField(
            model_name='expensecategory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_categories', to=settings.AUTH_USER_MODEL),
        ),
    ]
