# Generated by Django 5.1 on 2024-09-17 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0002_goals_delete_financialgoal'),
    ]

    operations = [
        migrations.AddField(
            model_name='goals',
            name='amount_saved',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
