# Generated by Django 5.0.3 on 2024-07-18 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0002_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='total_income',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='income',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='needs_percentage',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=5),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='savings_percentage',
            field=models.DecimalField(decimal_places=2, default=20, max_digits=5),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='wants_percentage',
            field=models.DecimalField(decimal_places=2, default=30, max_digits=5),
        ),
    ]
