# Generated by Django 5.1 on 2024-09-23 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='investment',
            options={'ordering': ['date'], 'verbose_name_plural': 'Investments'},
        ),
    ]
