# Generated by Django 5.0.3 on 2024-07-10 18:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='due_date',
            field=models.DateField(default=datetime.date(2024, 7, 10)),
        ),
    ]
