# Generated by Django 5.0.3 on 2024-07-12 08:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debt', '0003_alter_debt_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debt',
            name='due_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
