# Generated by Django 5.0.3 on 2024-07-15 09:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debt', '0005_alter_debt_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='amount_paid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='debt',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='debt',
            name='due_date',
            field=models.DateField(default=datetime.date(2024, 7, 15)),
        ),
    ]
