# Generated by Django 5.0.3 on 2024-07-18 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debt', '0006_debt_amount_paid_debt_is_paid_alter_debt_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debt',
            name='due_date',
            field=models.DateField(),
        ),
    ]
